import { uniqueId, NodeDefinition, RelationshipRule } from 'common';

export {
  provenanceNodes,
  studies,
  informationFields,
  informationRelationships,
  dependencyRelationships,
} from './assets/web-provenance-export.json';

// Definitions
const researchQuestion: NodeDefinition = {
  id: 'Research Question',
  classification: 'entity',
  //labelFormatString: "RQ${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "RQ${version}",
  informationFields: ["Description"]
}

const assumption: NodeDefinition = {
  id: 'Assumption',
  classification: 'entity',
  //labelFormatString: "A${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "A${version}",
  informationFields: ["Description"]
}

const requirement: NodeDefinition = {
  id: 'Requirement',
  classification: 'entity',
  //labelFormatString: "R${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "R${version}",
  informationFields: ["Description"]
}

const experiment: NodeDefinition = {
  id: 'Experiment',
  classification: 'entity',
  //labelFormatString: "E${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "E${version}",
  informationFields: ["Description"]
}

const data: NodeDefinition = {
  id: 'Data',
  classification: 'entity',
  //labelFormatString: "D${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "D${version}",
  informationFields: ["Description"]
}

const qualitativeModel: NodeDefinition = {
  id: 'Qualitative Model',
  classification: 'entity',
  //labelFormatString: "QM${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "QM${version}",
  informationFields: ["Description", "Species,dog,cat,armadillo,tiger"]
}

const simulationModel: NodeDefinition = {
  id: 'Simulation Model',
  classification: 'entity',
  //labelFormatString: "SM${version}${study ? ' (' + study.source  + ')' : ''}",
  labelFormatString: "SM${version}",
  informationFields: ["Description"]
}

const buildingActivity: NodeDefinition = {
  id: 'Building Simulation Model',
  //label: 'BSM',
  labelFormatString: "BSM${version}",
  classification: 'activity',
  informationFields: ["Description"]
}

const calibratingActivity: NodeDefinition = {
  id: 'Calibrating Simulation Model',
  //label: 'CSM',
  labelFormatString: "CSM${version}",
  classification: 'activity',
  informationFields: ["Description"]
}

const validatingActivity: NodeDefinition = {
  id: 'Validating Simulation Model',
  //label: 'VSM',
  labelFormatString: "VSM${version}",
  classification: 'activity',
  informationFields: ["Description"]
}

const analyzingActivity: NodeDefinition = {
  id: 'Analyzing Simulation Model',
  //label: 'ASM',
  labelFormatString: "ASM${version}",
  classification: 'activity',
  informationFields: ["Description"]
}

export const rules: RelationshipRule[] = [
  {
    id: 'data-was-derived-from-experiment',
    type: ['Derived from'],
    cardinality: 'one-to-one',
    source: data.id,
    target: experiment.id,
  },
  {
    id: 'experiment-was-generated-by-building-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: buildingActivity.id,
  },
  {
    id: 'experiment-was-generated-by-calibrating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: calibratingActivity.id,
  },
  {
    id: 'experiment-was-generated-by-validating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: validatingActivity.id,
  },
  {
    id: 'experiment-was-generated-by-analyzing-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: analyzingActivity.id,
  },
  {
    id: 'data-was-generated-by-building-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: buildingActivity.id,
  },
  {
    id: 'data-was-generated-by-calibrating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: calibratingActivity.id,
  },
  {
    id: 'data-was-generated-by-validating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: validatingActivity.id,
  },
  {
    id: 'data-was-generated-by-analyzing-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: data.id,
    target: analyzingActivity.id,
  },
  {
    id: 'qualitative-model-was-generated-by-building-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: qualitativeModel.id,
    target: buildingActivity.id,
  },
  {
    id: 'qualitative-model-was-generated-by-calibrating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: qualitativeModel.id,
    target: calibratingActivity.id,
  },
  {
    id: 'qualitative-model-was-generated-by-validating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: qualitativeModel.id,
    target: validatingActivity.id,
  },
  {
    id: 'simulation-model-generated-by-building-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: simulationModel.id,
    target: buildingActivity.id,
  },
  {
    id: 'simulation-model-generated-by-calibrating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: simulationModel.id,
    target: calibratingActivity.id,
  },
  {
    id: 'simulation-model-generated-by-validating-activity',
    type: ['Generated by'],
    cardinality: 'one-to-one',
    source: simulationModel.id,
    target: validatingActivity.id,
  },




  {
    id: 'building-activity-used-research-question',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: researchQuestion.id,
  },
  {
    id: 'building-activity-used-assumption',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: assumption.id,
  },
  {
    id: 'building-activity-used-requirement',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: requirement.id,
  },
  {
    id: 'building-activity-used-experiment',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: experiment.id,
  },
  {
    id: 'building-activity-used-data',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: data.id,
  },
  {
    id: 'building-activity-used-qualitative-model',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: qualitativeModel.id,
  },
  {
    id: 'building-activity-used-simulation-model',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: buildingActivity.id,
    target: simulationModel.id,
  },
  {
    id: 'calibrating-activity-used-simulation-model',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: calibratingActivity.id,
    target: simulationModel.id,
  },
  {
    id: 'validating-activity-used-simulation-model',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: validatingActivity.id,
    target: simulationModel.id,
  },
  {
    id: 'analyzing-activity-used-simulation-model',
    type: ['Used'],
    cardinality: 'one-to-many',
    source: analyzingActivity.id,
    target: simulationModel.id,
  },
  {
    id: 'calibrating-activity-used-data-for-calibration',
    type: ['Used for calibration'],
    cardinality: 'one-to-many',
    source: calibratingActivity.id,
    target: data.id,
  },
  {
    id: 'validating-activity-used-data-for-validation',
    type: ['Used for validation'],
    cardinality: 'one-to-many',
    source: validatingActivity.id,
    target: data.id,
  },
  {
    id: 'validating-activity-used-data-for-comparison',
    type: ['Used for comparison'],
    cardinality: 'one-to-many',
    source: validatingActivity.id,
    target: data.id,
  }
]

export const definitions: NodeDefinition[] = [
  researchQuestion,
  assumption,
  requirement,
  experiment,
  data,
  qualitativeModel,
  simulationModel,
  buildingActivity,
  calibratingActivity,
  validatingActivity,
  analyzingActivity,
]