export type Relationship =
  'Was generated by' |
  'Derived from' |
  'Used' |
  'Used for calibration' |
  'Used for validation';

export type RelationshipColors = { [r in Relationship]: string };

export const relationshipColors: RelationshipColors = {
  'Was generated by': 'blue',
  'Derived from': 'blue',
  'Used': 'blue',
  'Used for calibration': 'red',
  'Used for validation': 'green',
};
