export type NodeRelationship =
  'Was generated by' |
  'Derived from' |
  'Used' |
  'Used for calibration' |
  'Used for validation';

export type NodeType = 'activity' | 'entity';

export type RelationshipColors = {
  [r in NodeRelationship]: { color: string, source: NodeType, target: NodeType }
};

export const relationshipColors: RelationshipColors = {
  'Was generated by': {
    color: 'blue',
    source: 'entity',
    target: 'activity',
  },
  'Derived from': {
    color: 'blue',
    source: 'entity',
    target: 'entity',
  },
  'Used': {
    color: 'blue',
    source: 'activity',
    target: 'entity',
  },
  'Used for calibration': {
    color: 'red',
    source: 'activity',
    target: 'entity',
  },
  'Used for validation': {
    color: 'green',
    source: 'activity',
    target: 'entity',
  },
};
